In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(20)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr = np.arange(0, 10, 3)

In [7]:
arr

array([0, 3, 6, 9])

In [9]:
arr = np.arange(1, 10 ,0.5)

In [10]:
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [11]:
arr = np.arange(1,10)

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr_new = np.arange(9)

In [15]:
arr_new.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr = np.arange(1, 37)

In [17]:
arr.reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [18]:
ar = np.arange(10)

In [19]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(ar)

numpy.ndarray

In [21]:
ar1 = np.arange(20)

In [22]:

ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
ar = np.arange(0, 10)

In [24]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ar = np.arange(0,10,3)

In [26]:
ar

array([0, 3, 6, 9])

In [27]:
ar =np.arange(1, 20 ,2)

In [28]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
ar = np.arange(1, 21, 2)

In [30]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
ar = np.arange(0, 20, 2)

In [32]:
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
ar = np.arange(0, 21, 2)

In [34]:
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
ar = np.arange(1, 10, .5)

In [36]:
ar

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [38]:
ar = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
ar.shape

(3, 3)

In [44]:
ar_new = np.arange(9)

In [45]:
ar_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
ar_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
ar_new.ndim

1

In [48]:
ar_new.shape

(9,)

In [49]:
ar_new.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
ar_new = ar_new.reshape(3,3)

In [51]:
ar_new

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
ar_new.shape

(3, 3)

In [53]:
ar = np.arange(1,10)

In [54]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
ar = ar.reshape(3,3)

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar.size

9

In [58]:
ar_new.size

9

In [59]:
ar_test = np.arange(1, 10)

In [60]:
ar_test

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
ar_test = ar_test.reshape(3,3)

In [62]:
ar_test

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr = np.arange(1, 37)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [65]:
arr = arr.reshape(6,6)

In [66]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [67]:
arr = np.arange(100).reshape(10,10)

In [68]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
arr.size

100

In [70]:
arr.ndim

2

In [71]:
arr = arr.reshape(5,5,4)

In [72]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [73]:
ar = np.arange(12).reshape(3, 4)

In [74]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
ar1 =ar.reshape(-1,1)

In [76]:
ar1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [77]:
ar1_test = ar.reshape(2,-1)

In [78]:
ar1_test

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
ar2 = ar.reshape(-1,2)

In [80]:
ar1xar2 = np.dot(ar1_test, ar2)

In [81]:
ar1xar2

array([[110, 125],
       [290, 341]])

In [82]:
ar1xar2.size

4

In [83]:
ar1 = ar.reshape(6,-1)

In [84]:
ar2 = ar.reshape(-1, 6)

In [85]:
ar2, ar1

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [86]:
ar1xar2 = np.dot(ar1, ar2)

In [87]:
ar1xar2

array([[  6,   7,   8,   9,  10,  11],
       [ 18,  23,  28,  33,  38,  43],
       [ 30,  39,  48,  57,  66,  75],
       [ 42,  55,  68,  81,  94, 107],
       [ 54,  71,  88, 105, 122, 139],
       [ 66,  87, 108, 129, 150, 171]])

In [88]:
areye = np.eye(6)

In [89]:
areye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [101]:
ar = np.arange(1, 20, 1)

TypeError: 'tuple' object is not callable

In [102]:
del arange

NameError: name 'arange' is not defined

In [103]:
del arange

NameError: name 'arange' is not defined

In [104]:
del np
import numpy as np

In [107]:
aaa = np.arange(37).reshape(6,6)

TypeError: 'tuple' object is not callable

In [93]:
ar1

(6, 6)